#+TITLE: A little bit of Everything
#+AUTHOR: Orgzly
#+OPTIONS: html-postamble:nil num:nil H:10

* Notebooks Sync

You can store your notebooks on Dropbox or sync them with a directory
on your device.

Notebooks are written as plain-text files in [[http://orgmode.org][Org mode]] file format.

Synchronization is currently manual -- you have to initiate it
yourself by clicking the /Sync/ button. Button is located in the
navigation drawer.

** Repository Types
*** Dropbox

 You have to specify a directory for storing your notebooks in.

 - Go to /Settings/
 - Click on /Repositories/
 - Click the plus icon and choose /Dropbox/
 - Enter the directory inside Dropbox (without "Dropbox" part)

*** Device (local storage)

 Notebooks can be synced with one or more directories on your device.

 - Go to /Settings/
 - Click on /Repositories/
 - Click the plus icon and choose /Device Storage/
 - Click /Browse/ and select (or create new) directory

** Status Messages

After syncing is done, every notebook will have its sync status
message updated.

*** No change

Notebook is already synced. Nothing to do.

*** Saved to /URL/

Notebook has been successfully synced by being saved to the repository
represented by /URL/.

*** Loaded from /URL/

Notebook has been successfully synced by being loaded from the
notebook represented by /URL/.

*** Notebook has no link and one or more remote notebooks with the same name exist

Orgzly doesn't know which remote notebook to use for syncing.

Each notebook must have a link to a remote notebook. Link is
usually set automatically after the first sync. However, there are
cases when this is not possible, or when the link is removed.

Link can not be created after the first sync if:

- Notebook was created in Orgzly, but there is already a remote
  notebook with the same name in one of the repositories
- Multiple repositories are used and there is a notebook with the same
  name in them

Link is removed when:

- Repository is renamed or deleted

Link can be set manually:

- Open the list of notebooks ("Notebooks")
- Long-click on a notebook
- Click on /Set Link/
- Choose a repository
- Click /Set/

Link is set if you can see the URL next to the small link icon in
notebook's details.

*** Notebook has no link and multiple repositories exist

See [[Notebook has no link and one or more remote notebooks with the same name exist]].

*** Both local and remote notebook have been modified
:PROPERTIES:
:CUSTOM_ID: Both-local-and-remote-notebook-have-been-modified
:END:

If you modify a notebook in Orgzly and at the same time (before
performing a sync) you modify its linked remote notebook, next sync
will leave the notebook in a conflicted state.

When notebook is not synced due to conflict, you have two options:

- /Force Load/ to import remote notebook and overwrite the local version
- /Force Save/ to export local notebook and overwrite the remote version

These actions are available in notebook's contextual menu:

- Open the list of notebooks ("Notebooks")
- Long-click on a notebook to open the menu

There is currently no other way to resolve a conflict within Orgzly itself.
 
**** Manually merging the two, conflicting files when using Dropbox
 
When the local and remote notebooks have been modified in a Dropbox
repository you can take advantage of the facts that Orgzly stores
information in text files (in the Org file format) and that Orgzly
will create a new copy of the file if you remove it from Dropbox.
 
For example, you might move the original, underlying .org file in
Dropbox to a different directory, then tell Orgzly to sync the files
again (which will cause Orgzly to create a new file (with the same
file name)).  You can then use an external tool (such as a diff
program) to compare your original file and the file that Orgzly
created.  You can then determine what changes were made, and which
ones you wish to keep.
 
Be sure to remember that the new file (the one created by Orgzly) is
where you want to put your final, merged version of the file.

** Notes for Org mode users

Notebooks are encoded in [[http://orgmode.org][Org mode]] file format.

*** Generated Org files

When compared to your original Org files, files generated by Orgzly
might differ in the amount of white space, outlined below. Any other
difference would be considered a serious bug.

- /Tags are separated from title with a single space character./ You
  will lose your tags' indentation, as if you had ~org-tags-column~
  set to ~0~.

- /Unsupported metadata below header is part of note's content./ As
  soon as any unsupported metadata is encountered, lines from that point
  until the next heading are considered part of note's content.  You
  might find an unexpected new line between supported and unsupported
  metadata, because note's content is normally separated from heading
  by a new line.

If any of this is not working for you, please [[Contact][contact]] us.

* Search
:PROPERTIES:
:CUSTOM_ID: Search
:END:

Search expressions are separated with space. They are joined by
logical /AND/. /OR/ operator is not yet supported.

Words are searched within notes' /title/, /content/ and /tags/.

** Search operators

|--------------+------------------------------+-------------------------|
| Operator     | Finds notes                  | Examples                |
|--------------+------------------------------+-------------------------|
| ~s.DAY~      | Scheduled for day or earlier | ~s.today~ ~s.1w~        |
| ~d.DAY~      | Deadline on day or earlier   | ~d.tmrw~                |
| ~i.STATE~    | With state                   | ~i.todo~ ~i.next~       |
| ~.i.STATE~   | Without state                | ~.i.done~ ~.i.canceled~ |
| ~b.NOTEBOOK~ | From notebook                | ~b.Work~ ~b.Home~       |
| ~t.TAG~      | With tag                     | ~t.sport~ ~t.project~   |
| ~p.PRIORITY~ | Having priority              | ~p.a~ ~p.c~             |
|--------------+------------------------------+-------------------------|

*DAY* can be ~today~, ~tod~, ~tomorrow~, ~tmrw~, ~tom~ or denoted by:
  - Nd -- N days from today (~1d~, ~5d~, ...)
  - Nw -- N weeks from today (~2w~)
  - Nm -- N months from today (~3m~)
  - Ny -- N years from today (~1y~)

*STATE* is a keyword like =TODO=, =DONE=, =NEW=, etc. Case is irrelevant.
Only states listed in 'Settings -> Notes -> States' can be searched by. Any
keywords not included in the settings are not treated as states, but just become
part of the note title.

*NOTEBOOK* is the name of notebook. It must be surrounded with double
quotes if it contains spaces.

*TAG* is searched as a substring. For example ~t.bee~ will find notes
which are tagged with =beeblebrox=.

*PRIORITY* is a priority starting from ~A~.

** Sorting

Notes are sorted by notebook name then priority. If =s= or =d= are
used in the query, they are also sorted by scheduled or deadline
time. They are always sorted by position in the notebook last.

You can change this behavior by using =o= operator.

| =o.PROPERTY=  | sort by property                 |
| =.o.PROPERTY= | sort by property (reverse order) |

Following properties are supported:

| =b=  =book=  =notebook=        | notebook name  |
| =s=  =sched=  =scheduled=      | scheduled time |
| =d=  =dead=  =deadline=        | deadline time  |
| =p=  =pri=  =prio=  =priority= | priority       |

** Examples

- ~i.todo t.john~ -- Search for =TODO= notes which are tagged with =john=

- ~b.Work .i.done~ -- Search in notebook =Work= for notes that are not =DONE=

- ~b.Home buy~ -- Search in notebook =Home= for notes which contain the
  string =buy= in their title, content or any of the tags

- ~s.1d p.a~ -- Search for priority ~A~ notes scheduled for tomorrow or earlier (same as ~p.a s.tom~)

- =s.1d o.book o.pri= -- Search for notes scheduled for tomorrow sorting them by notebook name then priority

- =o.book o.pri o.s= -- Sort by notebook name then priority then scheduled time

** Search Results

Once you've run your search you'll be shown either a message telling you that your search did not match any notes, or else you'll be shown a list of the notes that did match your search. For each note you can tap on it to edit the note immediately.  For each note you can also swipe right to display a menu of options that allow you to assign a starting time, cycle through the =TODO= and =DONE= states, or to simply mark the note as =DONE=.  If you swipe left you'll be given a single option: displaying the note in the Notebook that contains it.  

** Future plans

See [[https://github.com/orgzly/documentation/blob/master/searching-proposal.org][Search queries syntax (Proposal)]].

* FAQ
:PROPERTIES:
:CUSTOM_ID: FAQ
:END:

** How much does it cost?
:PROPERTIES:
:CUSTOM_ID: Cost
:END:

Orgzly is free.

** Is the source code available?
:PROPERTIES:
:CUSTOM_ID: Source
:END:

Yes, it's available on [[https://github.com/orgzly/orgzly-android][GitHub]].

** Is there an iOS version?
:PROPERTIES:
:CUSTOM_ID: iOS
:END:

No, only Android version is available at the moment.

After implementing some of the important features which are still
missing in the current Android version, there is an idea to start
working on either iOS version or a Web application.

* Privacy Policy
** Other Data

When you give Orgzly access to Dropbox, an authentication token is
stored on your device to allow receiving and sending of notebooks from
and to Dropbox. No other data is being transferred. Your Dropbox
credentials are not visible to Orgzly.

* Contact
:PROPERTIES:
:CUSTOM_ID: Contact
:END:

Email us at [[mailto:support@orgzly.com][support@orgzly.com]] and visit [[http://www.orgzly.com][Orgzly.com]].

Follow us on [[https://twitter.com/Orgzly][Twitter]], [[https://plus.google.com/+Orgzly][Google+ Page]], [[https://plus.google.com/communities/104387367636243222968][Google+ Community]] and [[https://www.facebook.com/Orgzly][Facebook]].
