#+OPTIONS: html-postamble:nil num:nil html-style:nil tags:nil
#+TODO: FEAT IMPR FIX | DONE

* v1.4.7
:PROPERTIES:
:CUSTOM_ID: v147
:END:
** v1.4.7-beta.1 :preprod:
*** FEAT Delete note from note editor
*** IMPR All Toasts replaced with Snackbars
*** IMPR Various bug fixes and improvements

- Focus new property name
- Allow properties with no value
- Click dialog's positive button on keyboard action button press
- Debugging code removed from Directory repo (fix for slow sync)
- Fixed crash when pressing the back button in non-existent note
  (thanks for the report!)
- Target Android 7.1

* v1.4.6
:PROPERTIES:
:CUSTOM_ID: v146
:END:
** v1.4.6-beta.1 :preprod:
*** FEAT Search operators for sorting (~o~ and ~.o~)

Sorting from https://gist.github.com/nevenz/7a8377eafb1d9ed8ffae.
Except for ~-o~ support -- use ~.o~ instead for now.

*** FEAT Save note on keyboard's action button press

This allows much quicker note creation, as you don't need to move your
finger all the way to the top to save the note.

*** FEAT Separate notes with new-line or not (new option)

New setting with 3 possible values:

- Always
- Multi-line notes only
- Never

*** IMPR Dismiss Snackbar on any touch

*** IMPR Close drawer when Snackbar is displayed

After starting sync from the drawer, "No repos configured" Snackbar
was being displayed below drawer.

*** IMPR Syncing moved to new SyncService

No user visible changes yet, but this is the first step for auto-sync.

*** FIX Remove support for parsing =CLOCK= for now

No special handling of =CLOCK= entries for now, they are treated as
part of note's body for now.  Needs full =LOGBOOK= support to work
properly.

*** FIX Fix ~b~ search operator parsing (dot as a book name)
*** FIX Hide cycle-visibility menu item if book doesn't exist

* v1.4.5
:PROPERTIES:
:CUSTOM_ID: v145
:END:
** v1.4.5-beta.1 :preprod:
*** FEAT Show Snackbar after creating note and action to create another
*** IMPR Open note by clicking it from search results
*** IMPR Allow note content text to be selected, even if not in Edit mode
*** IMPR Enter Edit mode for new notes and when clicking note content
*** IMPR Open keyboard when switching to Edit mode
*** IMPR Check for storage permission before creating directory repo
*** FIX Encode Dropbox and directory repo URLs
*** FIX Fix possible crash when canceling sync
*** FIX Fix possible duplicates when searching using t operator
*** FIX Stop displaying only one title line

* v1.4.4
:PROPERTIES:
:CUSTOM_ID: v144
:END:
** v1.4.4-beta.1 :preprod:
*** FEAT Links (http and mailto) support in note editor

=http=, =https= and =mailto= are currently supported.  Both standalone
and within square brackets (both with and without the name).  In other
words:

#+BEGIN_EXAMPLE
http://www.orgzly.com
[[mailto:support@orgzly.com][Support]]
[[http://www.orgzly.com/help]]
#+END_EXAMPLE

should all work and be displayed as expected.

You can switch between editing and viewing note's content now.

*** FEAT Tags inheritance (~t~ operator)

~t.tag~ now searches for inherited tags as well.

*** FEAT Search by note's tag only (new tn operator)

This is what ~t.tag~ used to do.

*** FEAT Floating action button

For new notebooks, notes and saved searches.  It should be added for
repos as well.

Might be added for saving notes too, but it seems it's not
recommended.  So something else will be done to speed up the creation
of new notes (save on back, quick creation from the list like in
Todoist for example etc.)

* v1.4.3
:PROPERTIES:
:CUSTOM_ID: v143
:END:
** Quick-fix :preprod:
*** FIX Encode links of notebooks synced by older versions

* v1.4.2
:PROPERTIES:
:CUSTOM_ID: v142
:END:
** v1.4.2-beta.1 :preprod:
*** FEAT Renaming notebooks
*** FEAT UI for =PROPERTIES=
*** FEAT Chinese translation

Thanks to Dongbin Shi for reverse engineering the APK. :)

*** FIX Use first configured keyword when marking note as done

=DONE= was hardcoded, so if it wasn't in the list of done keywords,
clicking checkmark had no effect.

*** FIX Notebooks encoding fix when using directory repo type

* v1.4.1
:PROPERTIES:
:CUSTOM_ID: v141
:END:
** v1.4.1-beta.1 :preprod:

*** FEAT Sort notebooks by name (new option)
*** FEAT Support ~.b.notebook~ search expression
*** FEAT Prompt to save or discard changes on back press
*** FEAT Show snackbar on sync errors
*** IMPR Skip files starting with =.#= when syncing
*** IMPR Display new repo buttons instead of empty repository list
*** IMPR Display titles of notebooks in a list when sharing to Orgzly
*** IMPR Use Dropbox API v2

* v1.4
:PROPERTIES:
:CUSTOM_ID: v140
:END:
** v1.4-beta.4 :preprod:

*** FEAT Add "Fold content" option

Mentioned in another thread and requested elsewhere as well.  Folding
button will now be displayed even for notes without children and
content will be hidden if note is folded.

*** FEAT Add "Display content in search" option

Folding notes in search results doesn't make sense.  Since it's the
same flag as folding content, this option is added instead.

You can't hide/show content per note in search results, but you can
quickly open the note itself, so it should be OK.

*** IMPR Rearrange Settings

*** FEAT Update "What's New" dialog's button when DB upgrade is in progress

This is instead of displaying the toast when DB upgrade might take a
long time.  You won't notice anything unless you're upgrading from
previously released version.

*** IMPR Use large bullet for folded notes with children

Probably *too* large, but that might not be a bad thing. WorkFlowy's
bullets are nice, but I'd prefer not to use icons and ⦿ looks even
worse.  Might change (multiple times) in the future.

** v1.4-beta.3 :preprod:

*** FIX Fix table for those that had 1.4-beta.1 installed

** v1.4-beta.2 :preprod:
*** FIX Fix bullets text style
*** FIX Fix inserting timestamps to DB

Inserting times to DB was broken in some cases (due to
https://code.google.com/p/android/issues/detail?id=13045).

You might need to "Clear database" and re-import your notebooks, if you
notice something wrong with times.  Only affects users who had beta.1
installed.  There will be another beta after which this will not be
needed.

** v1.4-beta.1 :preprod:
*** FEAT Folding notes

DB upgrade can take some time if you have large files (due simple but
not very efficient SQL to set notes' parents).

Also, there's room for optimizations to speed up
moving/promoting/demoting/pasting which could be slow currently in some
cases.

*** FEAT List density: Comfortable, Cozy, Compact

/Comfortable/ layout is probably going to be changed to visually
separate title from tags, state etc. and have more cleaner multi-line
look.

/Cozy/ is default.

/Compact/ has no padding and allows displaying even more notes on the
screen.  Personally, I think there's never enough of them, so more
work's going to happen there, like an option to display title on a
single line ("This is a long title which ...") etc.

* v1.3.5
:PROPERTIES:
:CUSTOM_ID: v135
:END:
** v1.3.5-beta.1 :preprod:
*** FEAT Support ~d~ (deadline) search operator

Similar to ~s~ (scheduled).

*** FEAT Setting for selecting displayed notebook details

To avoid messy notebooks list. Default contains only few lines now.

*** FIX Allow years with more then 4 digits

Thanks to the immortal who used ~++100y~ and reported the crash.

*** IMPR Add confirmation of Dropbox unlinking
*** IMPR Trim notebook name
*** IMPR Hide import notebooks icon

Suggested by user to keep the same order of actions on both notebooks
and notebook views.

*** IMPR Lighter notebook sync error messages

With dark theme sync error messages were difficult to read.

*** IMPR Use compact notes list by default

* v1.3.4
:PROPERTIES:
:CUSTOM_ID: v134
:END:
** v1.3.4-beta.1 :preprod:
*** FEAT Support using Orgzly for "Note to self" voice action
*** FIX Fixed quick-menu opening (issue on some devices)
*** FIX Shift time at least once for =++= repeater
*** FIX Scroll to last note when opening quick-menu
*** IMPR "What's New" layout cleanup

* v1.3.3
:PROPERTIES:
:CUSTOM_ID: v133
:END:
** v1.3.3-beta.1 :preprod:
*** FIX Handle storage permission on Marshmallow

From v1.3.2 Orgzly doesn't require any permissions to be installed on
Marshmallow.  But if you want to export a notebook or use a Local
Directory repository type, you will be now asked to grant Storage
permission from within the app.

*** FIX Fixed title's auto-correction

Back to textMultiLine which seems to imply textAutoCorrect.

*** IMPR Smaller improvements

- Renames in various places:
  - Book -- Notebook (in sync status messages)
  - Use -- Select (in file browser)
  - Minimum -- Lowest (priority in settings)
  - Device Storage -- Local Directory (repo type)

- TextInputLayout usage in repo views (a.k.a. pretty hints)

* v1.3.2
:PROPERTIES:
:CUSTOM_ID: v132
:END:
** v1.3.2-beta.1 :preprod:

Mostly bug fixes.

API level has been updated to latest 23 (Marshmallow), as well as
support libraries' versions.

There is also some more under-the-hood work done for supporting
collapsing notes.

*** FEAT Support for right-to-left layouts

This probably has some design issues -- if you notice anything that
doesn't look as it should -- do tell.

*** IMPR Various bug fixes and improvements

- Issue with moving notes after using cut & paste
- Lingering CAB when creating note from quick-menu
- New-line replacing for title in note editor
- State color changes -- lighter for dark theme, darker for light

* v1.3.1
:PROPERTIES:
:CUSTOM_ID: v131
:END:
** v1.3.1-beta.1 :preprod:
*** FEAT Dark color scheme
*** IMPR Multiple ~.i~ expressions supported

* v1.3
:PROPERTIES:
:CUSTOM_ID: v130
:END:
** v1.3-beta.1 :preprod:

Minimum required Android version is now 4.0 "Ice Cream Sandwich".

Apologies to 1.47 % of users out there (per Google Play).  But dropping
support for older versions will allow quite a lot of code cleanup,
faster development and using some of the new features.  For example,
nice quick pickers for repeater editing.

*** FEAT Recurring tasks (repeater editing)

All 3 types are supported.

Probably a bit confusing for non-Org mode users.  A small description is
available as you cycle through different types and it includes terms
used in Org mode code as well (cumulate, catch-up, restart) which might
help a little.  Or confuse them more.

*** FEAT Saved searches editing

You can now create, edit, delete and re-position saved searches.

I will be posting a proposal for improving search queries soon, which
will make this feature quite powerful.

*** FEAT Done button in note's quick-menu

Quickly set note's state to DONE.  Added as cycling through states,
especially when using a repeater, felt kinda random (with more states).

*** FEAT Settings button in drawer
*** IMPR Larger font for note body and notebook description

* v1.2.2
:PROPERTIES:
:CUSTOM_ID: v122
:END:
** v1.2.2-beta.1 :preprod:
*** FEAT Large font size setting
*** FEAT Search operator ~p.priority~ added

Search by priority. See http://www.orgzly.com/help#Search.

*** FEAT Search operator ~s.day~ upgraded

Search by scheduled time -- ~s.2d~ will find those scheduled for the
day after tomorrow or earlier.  See http://www.orgzly.com/help#Search.

*** FIX Tags parsing

Previously, only =0-9a-zA-Z_@= were allowed when parsing tags.

You should be able to use any character (except space and colon) now.

*** FEAT Delete-note added to quick-menu
*** IMPR Various smaller improvements

- Move, Cut and Paste actions moved to overflow menu
- Icons for today, tomorrow and next-week changed
- Added warning about missing support for alarms
- Slightly darker todo keywords
- Removed horizontal line above quick-menu
- Do not allow empty note title when saving
- "Notebook's description" instead of "Add text to notebook"
- Few more tiny design changes here and there

* v1.2.1
:PROPERTIES:
:CUSTOM_ID: v121
:END:
** Quick-fix :preprod:
*** FIX Pressing Back not closing Search/CAB

Search and contextual action bar (displayed when notes are selected)
were not being closed after Back button press.

Crashes followed in most cases -- thanks for the reports!

Update to the latest Android Support Library caused this, which is now
downgraded.

* v1.2
:PROPERTIES:
:CUSTOM_ID: v120
:END:
** v1.2-beta.2 :preprod:
*** IMPR Open left-fling menu in Search

It contains a single button now -- open note.  This directly opens a
note from Search results.

I don't know if buttons for creating new notes should be added there.
On one hand it would be useful, on the other it would be confusing,
since newly created note might not even appear in the current view
(due to active search filter).

As mentioned, menus will become configurable, so perhaps it's best to
wait until then -- user will be able to add those buttons if he wants.

*** IMPR Icons changes

For:

- Next and previous state
- New note above/under/below

*** IMPR Thicker horizontal line above menu buttons

This line is likely to be removed, once more buttons are added.

** v1.2-beta.1 :preprod:
*** FEAT Swipe notes to open menus

This should speed up the usage a lot.

- Swipe note right :: menu for changing state and scheduling
- Swipe note left :: menu for creating new notes

One one menu can be opened at once, it stays opened when scrolling
through the notes and it can be closed by swiping in the same
direction the menu is for.

More buttons will be added, although goal is to make both menus
configurable -- you should be able to specify buttons you want in
there, including setting note to specific state (a la
TODO(t)).

Perhaps it could be even made horizontally scrollable, so that you can
have a lot more buttons available. It's probably much easier to click
in that area (near the note, where your attention already is) then top
of the device (action bar).

The original idea was to cycle through states by swiping, but:

- This wastes entire gesture on a single action
- Some of those state changes are not easily reversible (like setting
  a note with a repeater to DONE), so without undo support it's
  probably not a good idea to allow it -- it's too easy to swipe by
  mistake

*** FEAT Current location in app marked in drawer

Known searches are marked too, even if you enter them manually.

*** IMPR Use web page title when sharing to Orgzly

Web page's title ends up as note's title and URL is appended to note's
body.

*** FIX States' letters-only requirement removed

Previously, you could only use [A-Z] for state keywords (which was
obvious when you add a new keyword and re-parse notes).

This check is now removed.

*** IMPR Various smaller improvements

- Open keyboard automatically when creating new repo
- Description change when creating new repo
- Do not automatically open keyboard when sharing to Orgzly
- Last synced revision on its own line in notebook card
- Few design tweaks
  - Slightly stronger color used for selected notes
  - Blood red for notebook sync error
  - Lighter title and notebook-modified icon in notebook card

* v1.1.1
:PROPERTIES:
:CUSTOM_ID: v111
:END:
** v1.1.1-beta.1 :preprod:
*** FEAT Flagged unsynced notebooks

If notebook has been modified after the last sync, a small sync icon
is displayed (both in Notebooks and drawer).

*** FEAT Create directories from file browser

It is now possible to create new directories from "Device Storage"
sync method's browser.

*** FEAT Set creation time for notes (new option)

CREATED property is added.  Name of the property can be changed.
Timestamp includes time and it's inactive.

*** FEAT Delete remote notebooks (check-box)

When long-clicking a notebook and selecting "Delete", there is a
check-box now in the dialog.  If checked, remote notebook will be
deleted too.

This is currently done immediately, not on the next sync.

*** IMPR Drawer improvements

Visible changes:

- Searches are now under "Searches" (consistent with "Notebooks")
- Searches now scroll with notebooks

Together with changes under the hood, this will allow:

- Adding Settings to the drawer (requested some time ago)
- Clicking Searches to add, edit and delete searches
- Marking currently opened view in the drawer

*** IMPR Bug fixes and smaller improvements

- Bug left in the previous release is now fixed (opening different
  notebook while the list of notes is scrolling)

- Capitalize sentences in note's body and notebook's "preface"

- Share to Orgzly -- small look improvement for notebook selector (now
  wide and elevated)

* v1.1.0
:PROPERTIES:
:CUSTOM_ID: v110
:END:
** v1.1.0-beta.1 :preprod:
*** FEAT Sync with directories on your device

Browser is implemented.  You can't create new directories yet and
syncing of the deletion of notebooks is not yet possible.

Dropbox link/unlink button is moved from the main view of
repositories.

*** FEAT Options for more compact note list

Instead of (previously planned) option for Comfortable/Cozy/Compact
modes, two new options have been added:

- Compact list (use minimum height or not)
- Planning timestamps (display or not)

It's one additional option for more flexibility.

Maybe another one for truncating a heading (instead of wrapping) would
be useful...

*** IMPR Minor changes here and there

- Notebook's encodings are now one per row (used/detected).  Notebooks
  list is getting too messy, there'll be a new option added to hide
  all details except modification time for example.

- Settings status/action bar color change (again).

* v1.0.0
:PROPERTIES:
:CUSTOM_ID: v100
:END:
** v1.0.0-beta.7 :preprod:
*** FIX Importing chosen notebooks when using some apps

Fixes an issue when trying to import a notebook from Google Drive for
example.

Since file name is not available in all cases, a dialog with a
notebook name is now displayed after choosing a file.

*** FEAT Target API 22 (Android 5.1)
** v1.0.0-beta.6 :preprod:
*** FIX Timestamp parsing in some locales

Fixed an issue causing a crash in some locales.

*** FEAT Use =.org.txt= files too when syncing

In addition to files ending with =.org=, files ending with =.org.txt=
are now used as Org files when syncing.

** v1.0.0-beta.5 :preprod:
*** FEAT Display complete notes in notebooks and search results (new option)
*** FEAT Monospaced font for note body and notebook preface (new option)
*** FEAT Getting Started with Orgzly notebook included

Some *very* basic stuff for new users (in preparation for the production
release).  Shipped with the app (not downloaded or such).  It's just a
regular notebook -- you probably want to delete it if you don't want it
synced.

*** FEAT Restart Intros will immediately perform intros on click

Summary updated to explain everything that happens.  Useful if you
deleted Getting Started notebook and want the latest version
re-imported.

*** FIX Set Link now displays a currently set link
*** IMPR Various smaller improvements

- Removed horizontal dividers between notes
- Stronger bullet (to compensate for the above)
- Display bullet in search results too
- Notebook name in search results is now multi-line (not cut off)
- Notebook's name now displayed as a sub-title in some fragments
- Stopped showing URLs to linked notebooks (repos are enough)
- Deleting repo will remove any notebooks' links that used it
- Dropbox button look changed a bit

** v1.0.0-beta.4 :preprod:
*** FEAT Creating new notes above, under or below selected

The way this works now might be changed in the future:

- New note under selected could create it as a last child, not first
- New note below selected could skip all children

I think that would make more sense?

In any case, any changes there won't happen before support for
collapsing notes, as the work is similar (recognizing children and
such).

*** FEAT Keeping indentation in notebooks

Indentation is now detected while parsing and used when exporting the
same notebook.  It might become configurable in the future, as it's
closely related to ~org-indent-mode~ anyway.

*** IMPR Character encoding detection changed

Old method was failing to detect character encoding for some files.
UTF-8 is used by default, resulting in mojibake (noticed first for
=worg/org-blog-articles.org=).

*** FEAT Character encoding displayed for each notebook

Both used and detected.  Detected might not exist.

*** FIX Inserting previously deleted repo URL

This was causing a crash.

*** FEAT Repo and notebook URLs displayed for each notebook

Separate icons are now used for links and synced-to notebooks.

*** FEAT Displaying notebook's file name below title

If #+TITLE is not set, only file name is displayed.

*** IMPR Few design changes

- Notes
  - Bullet before title (might not be an improvement, but something
    will be necessary as an indicator, when note collapsing is
    implemented)
  - Lighter state (not bold)
  - More vertical spacing for times
- Note
  - Icons for save and cancel simplified (check mark and x mark now)
  - Timestamp buttons changed a bit
- Color of action and status bar for Settings changed

** v1.0.0-beta.3 :preprod:
*** FEAT Share to Orgzly

You can now use the standard share button from other apps to share
(text) to Orgzly.  This will create a new note and store text as a
title.

There will be more things to be done here, like allowing to store text
as a note content, picking a specific note to store it in, or creating
a new note at specific position.

*** FEAT Support for =#+TITLE=

Title is now read from "preface" (text before the first note) and used 
wherever appropriate instead of the file name. 

Existing notebooks you have will not see it -- you have to either 
re-import the notebooks or just start editing the preface and hitting 
the save icon. 

*** FEAT Selecting default state for new notes

In settings, TODO is not the only state you can use for new notes
anymore.  You can now select one of states you have in your "TODO
States" list.

*** FIX Marking notes with repeaters as done

This should be fixed now and act as expected (shifting times and
keeping states).  ~+~, ~.+~ and ~++~ are all supported.  State change
is not yet recorded.

*** IMPR Sort order in searches

- To Do :: notebook, priority, position 
- Scheduled :: notebook, priority, scheduled time, position 

Still not quite what Org mode does (taking repeaters into account
etc.) but getting there.

*** IMPR Smaller fixes and improvements

- Dropbox button buttonified 
- Repository create/edit dialog simplified 
- "What's new" instead of "Version" in Settings (being clickable) 
- Time in timestamp dialog kept when toggling it 
- Time and date in timestamp dialog format change (depends on locale) 
- Notebook's sync status removed (=NO_CHANGE= & friends). It was used
  only for tests -- unique "info" (i) messages are now used instead.

** v1.0.0-beta.2 :preprod:
*** FIX Database-related fix for older devices

Old sqlite version and unimplemented feature used.

*** IMPR Display repeater and delay in time stamps
*** IMPR Removed repeater from timestamp dialog

Not implemented yet.

*** IMPR Unused libraries removed

Apk size down to 1.1 MB from previous 10 MB.

*** IMPR Notebook renaming option removed

Needs more testing and some cases covered, related to syncing.

